baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Photolog'

[[menus.main]]
name = 'Gallery'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[params]
  [params.sidebar]
    [params.sidebar.profile]
      enabled = true
      src = "img/profile.jpg"