name = 'Photolog'
license = 'MIT'
licenselink = 'https://github.com/mk0218/photolog/blob/main/LICENSE'
description = 'Photolog is a Hugo theme for photographers.'

homepage = 'https://github.com/mk0218/photolog'

tags = ['blog', 'gallery']
features = ['some', 'awesome', 'features']

[author]
  name = 'Kim Minkyoung'
  homepage = 'https://mk0218.github.io/'

